[package]
name = "yatima-runtime"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yatima-core = { path = "../core", features = ["std"]}
sp-std = { version = "3" }
