[package]
name = "rust_example"
version = "0.1.0"
authors = ["rhysd <https://rhysd.github.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
